# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vitor Sales
email: 
description:  Formado em Análise e Desenvolvimento de sistemas, apaixonado por desenvolvimento front-end.
baseurl: "https://tvitor.github.io/" # "/jekyll-wing-template" the subpath of your site, e.g. /blog
url: "https://tvitor.github.io/" # the base hostname & protocol for your site
twitter_username: stvitor
github_username:  tvitor

# Build settings
markdown: kramdown
